/* 科研 idea 评审问卷 —— 前端。
 *
 * 数据流：items.json(题面，公开) + Apps Script(题序、已答、写回)。
 * 机器判定与「真实论文 / agent」标签不在这里，也不该在这里。
 *
 * POST 一律用 Content-Type: text/plain —— Apps Script 没有 doOptions，
 * 用 application/json 会触发 preflight 然后 CORS 失败。
 */
'use strict';

const CFG = window.SURVEY_CONFIG || {};

// 端点按问卷选，两份问卷各有各的 Apps Script 部署。问卷种类要到 boot() 里
// 解析完链接才知道，所以这两个值是 let，由 applyEndpoint() 落定。
let ENDPOINT = '';
let PREVIEW = true;

function applyEndpoint() {
  const map = CFG.ENDPOINTS || {};
  ENDPOINT = map[S.survey] || CFG.ENDPOINT || '';
  PREVIEW = !ENDPOINT;
}

const SESSION_ID = (() => {
  try {
    let s = sessionStorage.getItem('sid');
    if (!s) { s = Math.random().toString(36).slice(2, 10); sessionStorage.setItem('sid', s); }
    return s;
  } catch (e) { return Math.random().toString(36).slice(2, 10); }
})();

const S = {
  code: null, items: [], order: [], meta: {},
  answers: {}, idx: 0, finished: false,
  survey: 'judge', surveyTitle: '',
  // 交完之后点「重新填一份」时置真：下一次 join 不按名字接续，一定新建
  fresh: false,
};

/* 两份问卷共用这一个页面，靠邀请码分流：邀请码决定分到哪些题、看到哪段说明。
   受试者要求不一样，所以各发各的链接，互不相见。 */
const SURVEYS = {
  judge: {
    lang: 'en',
    bank: 'items.same-idea-judge.json',
    part: 'A',
    minPerItem: 0.75,      // 每题 3 格逐字段 + 整体 + 把握度，纯点选

    title: 'Same-Idea Judgement',
    blurb: 'We are measuring how human judgement compares with an automated judge, ' +
           'so there is <b>no answer key</b> — apply your own standard.',
  },
  quality: {
    lang: 'en',
    bank: 'items.idea-quality.json',
    part: 'B',
    mode: 'feed',          // 连续信息流；judge 仍走一题一屏的分页
    profile: true,         // 登记时问背景。judge 已发布、不再改，故只对本卷开
    showLength: false,     // 不在入口页报题数与时长


    minPerItem: 2,         // 读标题+摘要，八项点选，无文本框

    title: 'Idea Quality Review',
    blurb: 'Review each research idea the way you would review a submission. ' +
           'Some come from real papers, some were generated by a model — judge on ' +
           'content alone.',
  },
};

/* 界面文案按问卷语言切换。judge 那份全英文 —— 它的题干是从
   ar/evaluation/judging.py 的 build_judge_sys() 原文搬来的，
   中英混排会让「人看到的」和「模型看到的」再次漂移。 */
const STR = {
  zh: {
    privacy: '不收集个人身份信息，数据仅用于学术研究。点「开始」即表示同意参与，可随时退出。',
    len: (n, mins) => `共 ${n} 题，约 ${mins} 分钟，可分多次完成，答案自动保存。`,
    nameLabel: '你的名字', namePh: '留空 = 匿名',
    nameHint: '填了名字，换设备时打同样的名字就能接着上次继续。',
    start: '开始', resumeQ: '已经答过一半？',
    resumeA: '同一浏览器直接打开原链接就会接着上次的地方继续。换了设备或清过浏览器数据：' +
             '填了名字的，打同样的名字即可；匿名的，用左上角参与者编号找回记录。',
    prev: '← 上一题', next: '下一题 →', submit: '提交问卷',
    saved: '已保存', saving: '保存中…', offline: '未保存·重试中', preview: '预览模式',
    thanks: '已提交，谢谢', thanksBody: '答案已全部保存。可以关闭页面了。',
    again: '重新填一份', againNote: '会作为一份新的记录，不覆盖刚才提交的内容。',
    pidTitle: '参与者编号：换设备或清过浏览器数据时，用它找回记录',
    unfinished: (n) => `还有 ${n} 题没答完，先补齐才能提交。`,
    left: (n) => `还有 ${n} 项未填`,
    joinFail: '登记失败，请重试。',
    offline: '连不上问卷服务器，请检查网络后重试。',
    errTitle: '出错了', errBody: '刷新页面重试；若反复出现请联系研究者。',
    loading: '正在载入…', bankFail: '题库载入失败：',
    leftover: '还有答案没保存成功，请检查网络后再试。', submitFail: '提交失败：',
  },
  en: {
    privacy: 'No personally identifying information is collected; the data is used for ' +
             'academic research only. Clicking Start indicates your consent to take part. ' +
             'You may stop at any time.',
    len: (n, mins) => `${n} items, about ${mins} minutes. You can complete them in ` +
         `several sittings; answers save automatically.`,
    nameLabel: 'Your name', namePh: 'leave blank to stay anonymous',
    nameHint: 'If you give a name, entering the same name on another device resumes where you left off.',
    start: 'Start', resumeQ: 'Already partway through?',
    resumeA: 'Reopening the original link in the same browser resumes automatically. ' +
             'On another device, or after clearing browser data: if you gave a name, enter the ' +
             'same name; if you were anonymous, use the participant ID shown at the top left.',
    prev: '← Previous', next: 'Next →', submit: 'Submit',
    saved: 'Saved', saving: 'Saving…', offline: 'Not saved · retrying', preview: 'Preview mode',
    thanks: 'Submitted — thank you', thanksBody: 'All answers are saved. You can close this page.',
    again: 'Fill out another', againNote: 'Starts a separate record; it does not overwrite what you just submitted.',
    pidTitle: 'Participant ID — use it to recover your record on another device',
    unfinished: (n) => `${n} items are still incomplete. Please finish them before submitting.`,
    left: (n) => `${n} left on this item`,
    joinFail: 'Could not register. Please try again.',
    offline: 'Cannot reach the survey server. Check your connection and try again.',
    errTitle: 'Something went wrong', errBody: 'Refresh to retry; if it keeps happening, contact the researcher.',
    loading: 'Loading…', bankFail: 'Could not load the item bank: ',
    leftover: 'Some answers have not been saved yet. Check your connection and try again.',
    submitFail: 'Submit failed: ',
  },
};
const T = () => STR[(SURVEYS[S.survey] || SURVEYS.judge).lang] || STR.zh;

const $ = (id) => document.getElementById(id);
const el = (tag, cls, html) => {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (html != null) n.innerHTML = html;
  return n;
};
const esc = (s) => String(s).replace(/[&<>]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;' }[c]));

/* 标签页图标。两份问卷各一个，开着两个标签时一眼能分清是哪份。
   内联 SVG data URI —— 不额外请求文件，也不怕 Pages 的路径问题。 */
const FAVICON = {
  judge: 'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%3E%3Crect%20width%3D%2232%22%20height%3D%2232%22%20rx%3D%227%22%20fill%3D%22%233a4fa0%22%2F%3E%3Crect%20x%3D%226%22%20y%3D%228%22%20width%3D%228%22%20height%3D%2216%22%20rx%3D%222%22%20fill%3D%22%23ffffff%22%2F%3E%3Crect%20x%3D%2218%22%20y%3D%228%22%20width%3D%228%22%20height%3D%2216%22%20rx%3D%222%22%20fill%3D%22%23ffffff%22%20opacity%3D%22.55%22%2F%3E%3C%2Fsvg%3E',
  quality: 'data:image/svg+xml,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%2032%2032%22%3E%3Crect%20width%3D%2232%22%20height%3D%2232%22%20rx%3D%227%22%20fill%3D%22%238a4a86%22%2F%3E%3Crect%20x%3D%226%22%20y%3D%2218%22%20width%3D%225%22%20height%3D%228%22%20rx%3D%221.5%22%20fill%3D%22%23ffffff%22%20opacity%3D%22.55%22%2F%3E%3Crect%20x%3D%2213.5%22%20y%3D%2213%22%20width%3D%225%22%20height%3D%2213%22%20rx%3D%221.5%22%20fill%3D%22%23ffffff%22%20opacity%3D%22.78%22%2F%3E%3Crect%20x%3D%2221%22%20y%3D%227%22%20width%3D%225%22%20height%3D%2219%22%20rx%3D%221.5%22%20fill%3D%22%23ffffff%22%2F%3E%3C%2Fsvg%3E',
};
function setFavicon(survey) {
  const href = FAVICON[survey] || FAVICON.judge;
  let n = document.getElementById('favicon');
  if (!n) {
    n = document.createElement('link');
    n.id = 'favicon';
    n.rel = 'icon';
    document.head.appendChild(n);
  }
  n.href = href;
}

/* ------------------------------------------------------------------ 网络 */

function setSave(state, text) {
  const n = $('saveState');
  n.dataset.s = state;
  n.textContent = text || T()[state] || state;
}

/** 服务器答了但拒绝了（比如编号不存在）。这是正常状态，不是故障。 */
function rejected(msg) {
  const e = new Error(msg || 'rejected');
  e.rejected = true;
  return e;
}

async function apiGet(params) {
  const q = new URLSearchParams(params);   // 无共享 token：邀请码就是凭据
  const r = await fetch(`${ENDPOINT}?${q}`, { redirect: 'follow' });
  if (!r.ok) throw new Error('GET ' + r.status);
  const j = await r.json();
  if (!j.ok) throw rejected(j.error);
  return j;
}

async function apiPost(body) {
  const r = await fetch(ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'text/plain;charset=utf-8' },   // 不要改成 json
    redirect: 'follow',
    body: JSON.stringify({ code: S.code, session_id: SESSION_ID,
                           items_build: S.meta.build_hash || S.meta.build || '',
                           ...body }),
  });
  if (!r.ok) throw new Error('POST ' + r.status);
  const j = await r.json();
  if (!j.ok) throw rejected(j.error);
  return j;
}

/* 攒批发送。失败不丢答案：留在队列里退避重试，本地也留一份。 */
const Outbox = {
  pending: new Map(), timer: null, inflight: false,
  queue(entry) {
    if (PREVIEW) return;
    this.pending.set(entry.item_id, entry);
    this.persist();
    clearTimeout(this.timer);
    this.timer = setTimeout(() => this.flush(), 5000);
    setSave('saving');
  },
  async flush() {
    if (PREVIEW || this.inflight || !this.pending.size) return;
    const batch = [...this.pending.values()];
    this.inflight = true;
    try {
      await apiPost({ action: 'save', items: batch });
      // 期间又被改过的不能删，否则那次修改会丢
      batch.forEach(e => { if (this.pending.get(e.item_id) === e) this.pending.delete(e.item_id); });
      this.persist();
      setSave(this.pending.size ? 'saving' : 'saved');
    } catch (err) {
      console.warn('flush failed:', err);
      setSave('offline');
      clearTimeout(this.timer);
      this.timer = setTimeout(() => this.flush(), 15000);
    } finally { this.inflight = false; }
  },
  persist() {
    try { localStorage.setItem('outbox:' + S.code, JSON.stringify([...this.pending.values()])); }
    catch (e) { /* 隐身模式存不下就算了，服务端才是真相 */ }
  },
  restore() {
    try {
      const raw = localStorage.getItem('outbox:' + S.code);
      if (raw) JSON.parse(raw).forEach(e => this.pending.set(e.item_id, e));
      if (this.pending.size) this.flush();
    } catch (e) { /* 同上 */ }
  },
};

window.addEventListener('pagehide', () => {
  if (PREVIEW || !Outbox.pending.size) return;
  try {
    fetch(ENDPOINT, {
      method: 'POST', keepalive: true,
      headers: { 'Content-Type': 'text/plain;charset=utf-8' },
      body: JSON.stringify({ code: S.code, session_id: SESSION_ID,
                             items_build: S.meta.build_hash || S.meta.build || '',
                             action: 'save', items: [...Outbox.pending.values()] }),
    });
  } catch (e) { /* 卸载期发不出去也没辙，本地已存 */ }
});

/* -------------------------------------------------------------- 题面渲染 */

function fieldsHtml(schema) {
  return (S.meta.shown_fields || Object.keys(schema)).map(f => {
    const v = schema[f];
    const body = Array.isArray(v)
      ? `<ul>${v.map(x => `<li>${esc(x)}</li>`).join('')}</ul>`
      : esc(v);
    return `<div class="fld"><span class="k">${esc(f)}</span><div class="v">${body}</div></div>`;
  }).join('');
}

function scale(name, opts) {
  return `<div class="scale">${opts.map(o =>
    `<label><input type="radio" name="${name}" value="${esc(o.v)}"><em>${esc(o.t)}</em>` +
    (o.s ? `<span>${esc(o.s)}</span>` : '') + `</label>`).join('')}</div>`;
}
const n15 = (lo, hi) => [{ v: 1, t: '1', s: lo }, { v: 2, t: '2' }, { v: 3, t: '3' },
                         { v: 4, t: '4' }, { v: 5, t: '5', s: hi }];

/* judge 的逐字段输出是严格二值(true/false)，没有第三档 —— 解析不出时记为缺判，
   不是「说不准」。所以问卷这边也只给 Same / Different：给人一个模型没有的选项，
   那些格子就没有可比对象，只能整格丢掉。
   (Part B 的「看不出」是盲法操纵检查，与 judge 无关，保留。)

   逐字段判定不评 contribution_type：它只有五个取值、绝大多数是 method，
   判「相同」几乎必然为真，一致性读数会被它稀释成噪声。
   但它仍然要在左边的 schema 里显示 —— 它是读懂另外四个字段的上下文。 */
const NOT_RATED = ['contribution_type'];

/* 领域写全称。语料里的 theme 是目录名（mlsys 这类缩写），直接摆给受试者
   既不专业也影响「你对这个方向熟不熟」那一问的作答。 */
const AREA_NAMES = {
  auto_research: 'Automated Scientific Research',
  world_models: 'World Models',
  code_generation: 'Code Generation',
  mlsys: 'Machine Learning Systems',
};
function areaName(t) {
  return AREA_NAMES[t] || String(t || '').replace(/_/g, ' ');
}

/** 当前问卷里要评的字段（题面显示五个，评分不含 contribution_type）。 */
function ratedFields() {
  return S.meta.asked_fields ||
    (S.meta.shown_fields || []).filter(f => !NOT_RATED.includes(f));
}

/**
 * 一道题还缺哪些必答项。只看答案对象，不碰 DOM —— 提交前要把没打开过的题
 * 也检查一遍，那些题根本没有 DOM。
 */
function missingKeys(part, ans) {
  ans = ans || {};
  const need = part === 'A'
    ? [...ratedFields().map(f => 'f_' + f), 'same_idea', 'confidence']
    : ['soundness', 'presentation', 'contribution',
       'feasibility', 'success', 'rating', 'confidence',
       'guess_source', 'expertise'];
  const miss = need.filter(k => {
    const v = ans[k];
    return v === undefined || v === null || String(v).trim() === '';
  });
  return miss;
}

function renderA(it) {
  // 题面渲染走 shown_fields，逐字段判定走 asked_fields —— 两者不是一回事：
  // contribution_type 与 proposed_approach 只作上下文，不评。题库没声明
  // asked_fields 时退回「展示字段减去不评的」。
  const fields = S.meta.asked_fields ||
    (S.meta.shown_fields || []).filter(f => !NOT_RATED.includes(f));
  const left = `
    <div class="cmp">
      <div class="col a"><div class="colhead">SCHEMA A</div>${fieldsHtml(it.A)}</div>
      <div class="col b"><div class="colhead">SCHEMA B</div>${fieldsHtml(it.B)}</div>
    </div>`;

  // 右栏只有 400px，四列表格会挤成一团；改成一字段一块的竖排控件
  const blocks = fields.map(f => `
    <div class="fieldq"><span class="fname">${esc(f)}</span><div class="opts">
      <label class="opt"><input type="radio" name="f_${f}" value="same">Same</label>
      <label class="opt"><input type="radio" name="f_${f}" value="diff">Different</label>
    </div></div>`).join('');

  // 下面的措辞逐句照搬 ar/evaluation/judging.py 的 build_judge_sys(五字段轴)：
  // 人和模型必须拿到同一条指令，任何改写都会变成人机差异里说不清的一项。
  const right = `
    <div class="ans">
      <h4>Step 1 · Per-field judgement</h4>
      <p class="hint">For each field in turn, decide whether A and B are substantially the
        same <b>on that field alone</b>, as if the other fields were hidden from you.
        If a field has no corresponding content in A or B (including when both are missing
        or use the placeholder <code>None</code>), its verdict is <b>Different</b>.</p>
      ${blocks}
    </div>
    <div class="ans">
      <h4>Step 2 · Whole idea</h4>
      <div class="row">
        <div class="q">Do A and B describe the same core idea?
          <small>Same only if the two schemas address substantially the same
            <b>problem</b> AND propose substantially the same <b>approach</b>.
            This is your own judgement on the full schema, NOT a vote or an average over
            Step 1 — agreeing on problem, motivation, contribution_type alone is not enough.</small></div>
        ${scale('same_idea', [{ v: 'yes', t: 'Yes' }, { v: 'no', t: 'No' }])}
      </div>
      <p class="hint">In both steps: different wording, naming, or level of detail does not
        matter; merely sharing a topic, task, dataset, or a general technique family does
        <b>NOT</b> count as the same.</p>
      <div class="row">
        <div class="q">Confidence</div>
        ${scale('confidence', n15('not at all', 'very sure'))}
      </div>
    </div>`;
  return { left, right };
}

function renderB(it) {
  // 这一卷的题面是「标题 + 摘要 + schema」：先给人读原文，再给结构化拆解。
  const head = [
    it.theme ? `<div class="bmeta">${esc(areaName(it.theme))}</div>` : '',
    it.title ? `<h3 class="btitle">${esc(it.title)}</h3>` : '',
    it.abstract ? `<div class="babs">${esc(it.abstract)}</div>` : '',
  ].join('');
  const left = head + (head ? '<div class="bsep">structured summary</div>' : '') +
               fieldsHtml(it.schema);

  // 第一组照搬 ICLR 2026 Official Review 的 Soundness / Presentation / Contribution，
  // 四档、措辞与官方一致 —— 受试者多半审过 ICLR，用他们熟悉的尺子噪声最小。
  const q4 = (name) => scale(name, [
    { v: 1, t: '1', s: 'poor' }, { v: 2, t: '2', s: 'fair' },
    { v: 3, t: '3', s: 'good' }, { v: 4, t: '4', s: 'excellent' }]);

  const right = `
    <div class="ans">
      <h4>Review dimensions · ICLR 2026 scale (1–4)</h4>
      <div class="row"><div class="q"><b>Soundness</b>
        <small>The soundness of the technical claims, experimental and research
          methodology, and whether the central claims are adequately supported
          with evidence.</small></div>
        ${q4('soundness')}</div>
      <div class="row"><div class="q"><b>Presentation</b>
        <small>The quality of the presentation: writing style and clarity, and
          contextualization relative to prior work.</small></div>
        ${q4('presentation')}</div>
      <div class="row"><div class="q"><b>Contribution</b>
        <small>The overall contribution to the research area. Are the questions
          important? Is there significant originality of ideas and/or execution?
          Are the results valuable to share with the broader community?</small></div>
        ${q4('contribution')}</div>
    </div>
    <div class="ans">
      <h4>Can it be done · will it work</h4>
      <div class="row"><div class="q"><b>Feasibility</b>
        <small>Could this experiment actually be carried out as described?</small></div>
        ${scale('feasibility', [{ v: 1, t: '1', s: 'not at all' }, { v: 2, t: '2', s: 'major cuts' },
                                { v: 3, t: '3', s: 'barely' }, { v: 4, t: '4', s: 'yes' },
                                { v: 5, t: '5', s: 'easily' }])}</div>
      <div class="row"><div class="q"><b>Expected success</b>
        <small>If carried out in full as planned, how likely is the main claim to hold?
          Separate from feasibility — ideas that are easy to run but unlikely to work
          are common.</small></div>
        ${scale('success', [{ v: 'p10', t: '<10%' }, { v: 'p10_30', t: '10–30%' },
                            { v: 'p30_50', t: '30–50%' }, { v: 'p50_70', t: '50–70%' },
                            { v: 'p70', t: '>70%' }])}</div>
    </div>
    <div class="ans">
      <h4>Overall</h4>
      <div class="row"><div class="q"><b>Rating</b>
        <small>Overall score, ICLR 2026 scale.</small></div>
        ${scale('rating', [
          { v: 0, t: '0', s: 'strong reject' },
          { v: 2, t: '2', s: 'reject' },
          { v: 4, t: '4', s: 'marg. below' },
          { v: 6, t: '6', s: 'marg. above' },
          { v: 8, t: '8', s: 'accept' },
          { v: 10, t: '10', s: 'strong accept' }])}</div>
      <div class="row"><div class="q"><b>Confidence</b>
        <small>5 = absolutely certain, familiar with the related work and checked the
          details; 3 = fairly confident, may have missed something; 1 = unable to
          assess this submission.</small></div>
        ${scale('confidence', [{ v: 1, t: '1' }, { v: 2, t: '2' }, { v: 3, t: '3' },
                               { v: 4, t: '4' }, { v: 5, t: '5' }])}</div>
      <div class="row"><div class="q">Which do you think this is?
        <small>Blinding check.</small></div>
        ${scale('guess_source', [{ v: 'paper', t: 'real paper' }, { v: 'agent', t: 'AI-generated' },
                                 { v: 'unsure', t: "can't tell" }])}</div>
      <div class="row"><div class="q">How familiar are you with
        <b>${esc(areaName(it.theme))}</b>?</div>
        ${scale('expertise', [{ v: 1, t: 'not at all' }, { v: 2, t: 'read in it' },
                              { v: 3, t: 'worked in it' }, { v: 4, t: 'published in it' }])}</div>
    </div>`;
  return { left, right };
}

/* ---------------------------------------------------------------- feed 模式 */

/* Part B 有 32 题、每题要读一段摘要。一题一屏 + 「下一题」按钮会把它变成
   32 次点击的表单苦役；连续信息流让人一路往下刷，答完一条自动滑到下一条。
   judge 那份仍走分页 —— 它已经在收数据，渲染路径一个字节都不动。 */

function feedCard(it, i) {
  const seq = String(i + 1).padStart(2, '0');
  const post = el('div', 'post');
  post.dataset.item = it.id;
  // 左：题面。右：评分。两栏并排，读与打分不用上下折返。
  post.innerHTML = `
    <div class="inner">
      <div class="phead">
        <span class="pseq">${seq}</span>
        ${it.theme ? `<span class="ptag">${esc(it.theme)}</span>` : ''}
        <span class="pdone">✓ done</span>
      </div>
      ${it.title ? `<h3>${esc(it.title)}</h3>` : ''}
      ${it.abstract ? `<div class="abs clamped">${esc(it.abstract)}</div>
                       <button class="more" type="button">Show more</button>` : ''}
      <details class="sch"><summary>Structured summary</summary>
        <div class="body">${fieldsHtml(it.schema)}</div></details>
    </div>
    <div class="rate">${renderB(it).right}</div>`;

  const abs = post.querySelector('.abs');
  const more = post.querySelector('.more');
  if (more) {
    more.addEventListener('click', () => {
      more.textContent = abs.classList.toggle('clamped') ? 'Show more' : 'Show less';
    });
  }
  return post;
}

function feedProgress() {
  const done = S.order.filter(answered).length;
  const n = S.order.length;
  const fill = document.getElementById('feedFill');
  if (fill) fill.style.width = `${(done / Math.max(1, n)) * 100}%`;
  const cnt = document.getElementById('feedCnt');
  if (cnt) cnt.textContent = `${done} / ${n}`;
  const btn = document.getElementById('feedSubmit');
  if (btn) btn.disabled = done < n;
}

/** 按问卷模式选渲染方式。judge = 分页，quality = 信息流。 */
function renderSurvey() {
  if (isFeed()) renderFeed(); else renderItem();
}

function renderFeed() {
  const main = $('main');
  main.classList.remove('wide');
  $('nav').hidden = true;

  const feed = el('div', 'feed');
  const cards = new Map();
  S.order.forEach((id, i) => {
    const it = S.items.find(x => x.id === id);
    if (!it) return;                      // 陌生题号略过，不拖垮整卷
    const card = feedCard(it, i);
    feed.appendChild(card);
    cards.set(id, card);
    writeItem(card, S.answers[id]);
    if (answered(id)) card.classList.add('done');

    const capture = () => {
      const ans = readItem(card);
      S.answers[id] = ans;
      const ok = missingKeys('B', ans).length === 0;
      const was = card.classList.contains('done');
      card.classList.toggle('done', ok);
      card.querySelectorAll('.missing').forEach(n => {
        if (n.querySelector(':checked') || n.querySelector('textarea')?.value.trim()) {
          n.classList.remove('missing');
        }
      });
      Outbox.queue({ item_id: id, part: 'B', answer: ans,
                     client_ts: new Date().toISOString(),
                     elapsed_ms: Date.now() - (seenAt.get(id) || Date.now()) });
      feedProgress();
      // 刚答完就滑到下一条，省掉「下一题在哪」这一步
      if (ok && !was) {
        const nx = card.nextElementSibling;
        if (nx) setTimeout(() => nx.scrollIntoView({ behavior: 'smooth', block: 'start' }), 280);
      }
    };
    card.addEventListener('change', capture);
    card.addEventListener('input', e => {
      if (e.target.tagName === 'TEXTAREA') capture();
    });
  });
  main.replaceChildren(feed);

  // 进入视野才开始计时：32 张卡一次渲染，否则后面的耗时全是假的
  if (window.IntersectionObserver) {
    const io = new IntersectionObserver(es => es.forEach(e => {
      const id = e.target.dataset.item;
      if (e.isIntersecting && !seenAt.has(id)) seenAt.set(id, Date.now());
    }), { threshold: 0.35 });
    cards.forEach(c => io.observe(c));
  }

  let bar = document.getElementById('feedBar');
  if (!bar) {
    bar = el('div', 'feedbar');
    bar.id = 'feedBar';
    bar.innerHTML = `<div class="wrap">
      <span class="cnt" id="feedCnt"></span>
      <span class="rest"><i id="feedFill"></i></span>
      <button class="primary" id="feedSubmit" disabled></button></div>`;
    document.body.appendChild(bar);
    bar.querySelector('#feedSubmit').addEventListener('click', () => $('btnFinish').click());
  }
  bar.hidden = false;
  bar.querySelector('#feedSubmit').textContent = T().submit;

  feedProgress();
  const first = S.order.findIndex(id => !answered(id));
  if (first > 0) cards.get(S.order[first])?.scrollIntoView({ block: 'start' });
}

/* ------------------------------------------------------------------ 界面 */

/**
 * 右侧评分栏的高度跟着左边题面走。
 *
 * 规则：评分栏自然高度 < 题面高度 → 钉住跟随，上限取「题面高度」与「视口可用高度」
 * 的较小者，读长 schema 时评分项始终在视野里。反之（评分项比题面还长，Part B 常见）
 * 就让它正常铺开 —— 钉住只会把一个本来一眼看完的表单塞进小滚动框。
 */
let rateSyncing = false;

function syncRate(card) {
  // 重入锁：ResizeObserver 盯着 .rate，而这个函数会改 .rate 的高度 —— 不挡住
  // 自己触发的那一轮回调就是个自激循环。锁到下一帧再放开，本轮改动引发的
  // 回调会在这之前送达，正好被吃掉。
  if (rateSyncing) return;
  const read = card.querySelector('.read');
  const rate = card.querySelector('.rate');
  if (!read || !rate) return;

  rateSyncing = true;
  try {
    if (window.matchMedia('(max-width:1040px)').matches) {   // 窄屏上下堆叠，不跟随
      rate.classList.remove('follow');
      rate.style.removeProperty('--rate-max');
      return;
    }
    rate.classList.remove('follow');          // 先还原，否则量到的是被裁过的高度
    rate.style.removeProperty('--rate-max');
    const readH = read.offsetHeight;
    const rateH = rate.offsetHeight;
    if (rateH < readH - 24) {                 // 24px 余量，免得两边差不多高时来回抖
      rate.style.setProperty('--rate-max',
        Math.min(readH, window.innerHeight - 150) + 'px');
      rate.classList.add('follow');
    }
  } finally {
    requestAnimationFrame(() => { rateSyncing = false; });
  }
}

let shownAt = Date.now();
// feed 模式下 32 张卡一次性渲染，得按「进入视野」各自计时
const seenAt = new Map();

function isFeed() {
  return (SURVEYS[S.survey] || {}).mode === 'feed';
}

function renderItem() {
  const id = S.order[S.idx];
  let it = S.items.find(x => x.id === id);
  if (!it) {
    // 兜底：题序里混进了本题库没有的题号。跳过它，别让整份问卷卡死在这一题。
    console.warn('题序里有未知题号，已跳过:', id);
    S.order = S.order.filter(x => S.items.some(y => y.id === x));
    if (!S.order.length) { forgetPid(); showJoin(); return; }
    S.idx = Math.min(S.idx, S.order.length - 1);
    it = S.items.find(x => x.id === S.order[S.idx]);
    if (!it) { showFatal(T().errBody); return; }
  }
  shownAt = Date.now();

  const parts = it.part === 'A' ? renderA(it) : renderB(it);
  const card = el('div', 'item');
  // 顺序是按人随机的，所以显示第几题(01/02…)而不是题号 A-02 —— 后者和底部
  // 「3 / 12」对不上，只会让人以为跳题了。真实 item_id 记在提交数据里。
  const seq = String(S.idx + 1).padStart(2, '0');
  card.innerHTML =
    `<div class="ihead"><span class="inum">${seq}</span></div>
     <div class="ibody" id="itemBody">
       <div class="stage">
         <div class="read">${parts.left}</div>
         <div class="rate">${parts.right}</div>
       </div>
     </div>`;

  const main = $('main');
  main.classList.add('wide');        // 答题屏用宽版容器
  main.replaceChildren(card);
  window.scrollTo(0, 0);

  const body = card.querySelector('#itemBody');
  writeItem(body, S.answers[it.id]);

  const capture = () => {
    const ans = readItem(body);
    S.answers[it.id] = ans;
    body.querySelectorAll('.missing').forEach(n => {
      if (n.querySelector(':checked') || n.querySelector('textarea')?.value.trim()) {
        n.classList.remove('missing');
      }
    });
    Outbox.queue({ item_id: it.id, part: it.part, answer: ans,
                   client_ts: new Date().toISOString(),
                   elapsed_ms: Date.now() - shownAt });
    updateProgress();
  };
  body.addEventListener('change', capture);
  body.addEventListener('input', e => { if (e.target.tagName === 'TEXTAREA') capture(); });

  // 题面高度会随字体加载、textarea 拉伸、窗口缩放变化，每次都要重量
  syncRate(card);
  if (window.ResizeObserver) {
    if (S._ro) S._ro.disconnect();
    S._ro = new ResizeObserver(() => syncRate(card));
    S._ro.observe(card.querySelector('.read'));
    S._ro.observe(card.querySelector('.rate'));
  }
  if (document.fonts && document.fonts.ready) {
    document.fonts.ready.then(() => syncRate(card)).catch(() => {});
  }

  $('counter').textContent = `${S.idx + 1} / ${S.order.length}`;
  $('btnPrev').disabled = S.idx === 0;
  const last = S.idx === S.order.length - 1;
  $('btnNext').hidden = last;
  $('btnFinish').hidden = !last;
  $('nav').hidden = false;
  updateProgress();
}

function partOf(id) {
  const it = S.items.find(x => x.id === id);
  return it ? it.part : 'A';
}

/** 全部必答项都填了才算这道题完成 —— 进度条与提交闸用的是同一个判据。 */
function answered(id) {
  return missingKeys(partOf(id), S.answers[id]).length === 0;
}

function updateProgress() {
  const done = S.order.filter(answered).length;
  $('progressBar').style.width = `${(done / Math.max(1, S.order.length)) * 100}%`;
  const miss = missingKeys(partOf(S.order[S.idx]), S.answers[S.order[S.idx]]);
  const t = T();
  $('leftCount').textContent = miss.length ? t.left(miss.length) : '';
}

/** 把缺的项标红并滚到第一个。只在用户试图前进时调用，不在作答过程中骚扰。 */
function flagMissing(keys, scope) {
  const body = scope || document.getElementById('itemBody');
  if (!body) return;
  body.querySelectorAll('.missing').forEach(n => n.classList.remove('missing'));
  let first = null;
  keys.forEach(k => {
    const input = body.querySelector(`[name="${CSS.escape(k)}"]`);
    if (!input) return;
    // textarea 不在 .row 里，直接标它自己
    const box = input.closest('.fieldq') || input.closest('.row') || input;
    box.classList.add('missing');
    if (!first) first = box;
  });
  if (first) first.scrollIntoView({ block: 'center', behavior: 'smooth' });
}

/** 登记页要报的题数：拆了卷就报单卷的题数，别报题库总量。 */
function formSize() {
  if (S.order.length) return S.order.length;
  const f = S.meta.forms;
  if (f) {
    const k = Object.keys(f);
    if (k.length) return f[k[0]].length;
  }
  return S.items.length;
}

function showJoin(msg) {
  $('nav').hidden = true;
  $('main').classList.remove('wide');
  const fb = document.getElementById('feedBar');
  if (fb) fb.hidden = true;
  const cfg = SURVEYS[S.survey] || SURVEYS.judge;
  const t = T();
  const p = el('div', 'panel');
  p.innerHTML = `
    <h2>${esc(cfg.title)}</h2>
    <p>${cfg.blurb}</p>
    <p>${t.privacy}${cfg.showLength === false ? '' : ' ' + t.len(formSize(),
        Math.max(1, Math.round(formSize() * (cfg.minPerItem || 1.8))))}</p>
    ${msg ? `<div class="note">${esc(msg)}</div>` : ''}
    <div class="row" style="margin-top:18px"><div class="q">${t.nameLabel}</div></div>
    <input type="text" id="nameIn" placeholder="${t.namePh}" maxlength="60" style="max-width:280px">
    <p style="font-size:12.5px;color:var(--ink3);margin-top:6px">${t.nameHint}</p>
    ${cfg.profile ? `<div id="profile">${profileHtml()}</div>` : ''}
    <p style="margin-top:14px"><button class="primary" id="joinGo">${t.start}</button></p>
    <details style="margin-top:14px">
      <summary style="cursor:pointer;font-size:12.5px;color:var(--ink3)">${t.resumeQ}</summary>
      <p style="margin-top:8px">${t.resumeA}</p>
    </details>`;
  $('main').replaceChildren(p);

  $('nameIn').addEventListener('keydown', e => { if (e.key === 'Enter') $('joinGo').click(); });
  $('joinGo').addEventListener('click', async () => {
    $('joinGo').disabled = true;
    const name = $('nameIn').value.trim();
    let profile = {};
    if (cfg.profile) {
      const root = $('profile');
      const miss = profileMissing(root);
      if (miss.length) {
        $('joinGo').disabled = false;
        root.querySelectorAll('.prow').forEach(n => n.classList.remove('missing'));
        miss.forEach(k => {
          const el0 = root.querySelector(`[name="${k}"]`) || $('areasOther');
          el0?.closest('.prow')?.classList.add('missing');
        });
        return;
      }
      profile = {
        position: root.querySelector('input[name="position"]:checked').value,
        review_exp: root.querySelector('input[name="review_exp"]:checked').value,
        areas: [...root.querySelectorAll('input[name="areas"]:checked')].map(i => i.value),
        areas_other: root.querySelector('#areasOther').value.trim(),
      };
    }
    if (PREVIEW) { S.code = 'PREVIEW'; showPid(); S.idx = 0; renderSurvey(); return; }
    try {
      // forms 非空时由后端轮转分配其中一份；前端只把候选交上去
      const r = await apiPost({ action: 'join', survey: S.survey, name,
                                fresh: S.fresh, ...profile,
                                items_build: S.meta.build_hash || '',
                                forms: S.meta.forms || null,
                                item_ids: S.items.map(i => i.id) });
      rememberPid(S.survey, r.code);
      // 带 ?p= 重载：新建和「按名字接续」走同一条恢复路径，答案回填不用写第二套
      const u = new URL(location.href);
      u.searchParams.set('p', r.code);
      location.href = u.toString();
    } catch (e) {
      $('joinGo').disabled = false;
      showJoin(e.rejected ? (e.message || t.joinFail) : t.offline);
    }
  });
}

/* 登记页的背景问题。
   资历与评审经验分成两问：合成一个量表就分不清「三年级博士但审过顶会」
   和「从没审过的 faculty」，而这两种人的评分基准完全不同。
   领域多选用的是本研究的四个主题，Other 留自填。 */
const PROFILE = {
  position: {
    label: 'Your position',
    opts: [['phd', 'PhD student'], ['postdoc', 'Postdoc'],
           ['faculty', 'Faculty'], ['industry', 'Industry researcher'],
           ['other', 'Other']],
  },
  review_exp: {
    label: 'Peer-review experience',
    opts: [['none', 'Never reviewed'], ['workshop', 'Workshop / journal'],
           ['conf', 'Reviewed for top-tier conferences'],
           ['ac', 'AC / SAC / PC at top-tier']],
  },
};
const AREA_OPTS = [
  ['auto_research', 'Automated Scientific Research'],
  ['world_models', 'World Models'],
  ['code_generation', 'Code Generation'],
  ['mlsys', 'Machine Learning Systems'],
];

function profileHtml() {
  const grp = (key, cfg) => `
    <div class="prow"><div class="plab">${cfg.label}</div>
      <div class="popts">${cfg.opts.map(([v, t]) =>
        `<label class="opt"><input type="radio" name="${key}" value="${v}"> ${esc(t)}</label>`
      ).join('')}</div></div>`;
  return `
    ${grp('position', PROFILE.position)}
    ${grp('review_exp', PROFILE.review_exp)}
    <div class="prow"><div class="plab">Which of these are you familiar with?
      <small>Select all that apply.</small></div>
      <div class="popts">${AREA_OPTS.map(([v, t]) =>
        `<label class="opt"><input type="checkbox" name="areas" value="${v}"> ${esc(t)}</label>`
      ).join('')}
      <label class="opt"><input type="checkbox" name="areas" value="other"> Other</label>
      <input type="text" id="areasOther" placeholder="which area?" maxlength="120"
             style="max-width:260px"></div></div>`;
}

/** 背景问题填全了没。没填全就不放行 —— 事后没法补问。 */
function profileMissing(root) {
  const miss = [];
  ['position', 'review_exp'].forEach(k => {
    if (!root.querySelector(`input[name="${k}"]:checked`)) miss.push(k);
  });
  const areas = [...root.querySelectorAll('input[name="areas"]:checked')].map(i => i.value);
  if (!areas.length) miss.push('areas');
  if (areas.includes('other') && !root.querySelector('#areasOther').value.trim()) {
    miss.push('areas_other');
  }
  return miss;
}

/* 左上角显示参与者编号 —— 换设备找回记录全靠它，所以要一直看得见。 */
/** 标题、语言、图标、导航按钮 —— 问卷种类一确定就全部就位，
    不能等到状态请求回来，否则登记页顶着 index.html 的静态默认值。 */
function applyChrome() {
  const cfg = SURVEYS[S.survey] || SURVEYS.judge;
  const t = T();
  document.querySelector('.bar .title').textContent = cfg.title;
  document.title = cfg.title;
  document.documentElement.lang = cfg.lang === 'en' ? 'en' : 'zh-CN';
  $('btnPrev').textContent = t.prev;
  $('btnNext').textContent = t.next;
  $('btnFinish').textContent = t.submit;
  setFavicon(S.survey);
}

function showPid() {
  const n = $('codePill');
  n.textContent = S.code;
  n.title = T().pidTitle;
  n.hidden = false;
}

/* 参与者编号按问卷分别记在本地：同一台机器可以先后做两份问卷，互不覆盖。 */
/** 丢掉当前身份：本地副本、URL 上的 ?p=/?code= 一起清掉。 */
function forgetPid() {
  try { localStorage.removeItem('pid:' + S.survey); } catch (e) { /* 无妨 */ }
  const u = new URL(location.href);
  u.searchParams.delete('p');
  u.searchParams.delete('code');
  history.replaceState(null, '', u);
  S.code = null;
  S.answers = {};
  $('codePill').hidden = true;
}

function rememberPid(survey, pid) {
  try { localStorage.setItem('pid:' + survey, pid); } catch (e) { /* 存不下不影响本次作答 */ }
}
function recallPid(survey) {
  try { return localStorage.getItem('pid:' + survey) || ''; } catch (e) { return ''; }
}

function showFatal(msg) {
  $('nav').hidden = true;
  $('main').classList.remove('wide');
  const fb = document.getElementById('feedBar');
  if (fb) fb.hidden = true;
  const t = T();
  $('main').replaceChildren(el('div', 'panel',
    `<h2>${t.errTitle}</h2><p>${esc(msg)}</p><p>${t.errBody}</p>`));
}

function showThanks() {
  $('nav').hidden = true;
  $('main').classList.remove('wide');
  const fb = document.getElementById('feedBar');
  if (fb) fb.hidden = true;
  const t = T();
  const p = el('div', 'panel');
  p.innerHTML = `<h2>${t.thanks}</h2>
    <p>${t.thanksBody}</p>
    <p style="margin-top:16px"><button id="againGo">${t.again}</button></p>
    <p style="font-size:12.5px;color:var(--ink3)">${t.againNote}</p>`;
  $('main').replaceChildren(p);
  $('againGo').addEventListener('click', () => {
    // 换一份全新记录：清掉本地 pid 和 URL 上的 ?p=，并让下一次 join 跳过按名字接续
    try { localStorage.removeItem('pid:' + S.survey); } catch (e) { /* 存不下也无妨 */ }
    const u = new URL(location.href);
    u.searchParams.delete('p');
    u.searchParams.delete('code');
    history.replaceState(null, '', u);
    S.fresh = true;
    S.code = null;
    S.answers = {};
    S.idx = 0;
    $('codePill').hidden = true;
    showJoin();
  });
}

/* ------------------------------------------------------------------ 启动 */

async function boot() {
  // 问卷种类由链接决定（?s=judge / ?s=quality），身份由 p= 或 localStorage 决定。
  const q = new URL(location.href).searchParams;
  S.survey = q.get('s') || q.get('survey') || 'judge';
  if (!SURVEYS[S.survey]) S.survey = 'judge';
  const cfg0 = SURVEYS[S.survey];

  let bank;
  try {
    bank = await (await fetch(cfg0.bank, { cache: 'no-cache' })).json();
  } catch (e) { showFatal(T().bankFail + e.message); return; }
  S.items = bank.items;
  S.meta = bank.meta || {};
  // ?code= 是预先生成的邀请码，仍然支持；?p= 是自助登记拿到的参与者编号
  S.code = (q.get('p') || q.get('code') || recallPid(S.survey) || '').trim().toUpperCase();
  applyEndpoint();                          // 端点随问卷走
  applyChrome();                            // 先定语言与标题，再渲染任何一屏
  setSave(PREVIEW ? 'preview' : 'saved');

  if (PREVIEW) {
    S.code = S.code || 'PREVIEW';
    S.order = S.items.map(i => i.id);
  } else {
    if (!S.code) { showJoin(); return; }
    let st;
    try {
      st = await apiGet({ action: 'state', code: S.code });
    } catch (e) {
      // 编号不存在(换过题库、清过表、链接手抄错)就当没带编号，安静回登记页；
      // 把它当错误弹给受试者只会让人以为自己做错了什么。
      if (e.rejected) {
        forgetPid();
        showJoin();
      } else {
        showJoin(T().offline);
      }
      return;
    }
    rememberPid(st.survey || S.survey, S.code);
    // 服务端存的题序可能来自另一版题库（题库换过、或这个编号是旧卷发的）。
    // 那种记录不能续答：它的答案对应的是别的题面。安静地让人重新登记，
    // 旧行仍留在表里，带着自己的 items_build，事后照样解得回去。
    const known = new Set(S.items.map(i => i.id));
    const srv = st.item_ids || [];
    const stale = srv.length && srv.some(id => !known.has(id));
    if (stale) {
      forgetPid();
      showJoin();
      return;
    }
    S.order = srv.length ? srv : S.items.map(i => i.id);
    S.survey = st.survey || 'judge';
    S.surveyTitle = st.survey_title || '';
    S.answers = st.answers || {};
    S.finished = !!st.finished_ts;
    Outbox.restore();
  }

  showPid();
  applyChrome();          // 服务端可能纠正了 survey，按最终值再刷一次

  if (S.finished) { showThanks(); return; }
  // 续答落到第一道没答的题
  const first = S.order.findIndex(id => !answered(id));
  S.idx = first < 0 ? 0 : first;
  renderSurvey();
}

$('btnPrev').addEventListener('click', () => { if (S.idx > 0) { S.idx--; renderItem(); } });
$('btnNext').addEventListener('click', () => {
  const id = S.order[S.idx];
  const miss = missingKeys(partOf(id), S.answers[id]);
  if (miss.length) { flagMissing(miss); return; }      // 必答项没填完不放行
  if (S.idx < S.order.length - 1) { S.idx++; renderItem(); }
});
$('btnFinish').addEventListener('click', async () => {
  const incomplete = S.order.filter(id => !answered(id));
  if (incomplete.length) {
    alert(T().unfinished(incomplete.length));
    const first = incomplete[0];
    if (isFeed()) {
      const card = document.querySelector(`.post[data-item="${CSS.escape(first)}"]`);
      if (card) {
        card.scrollIntoView({ behavior: 'smooth', block: 'start' });
        flagMissing(missingKeys('B', S.answers[first]), card);
      }
    } else {
      S.idx = S.order.indexOf(first);
      renderItem();
      flagMissing(missingKeys(partOf(first), S.answers[first]));
    }
    return;
  }
  if (!isFeed()) {
    const cur = S.order[S.idx];
    const curMiss = missingKeys(partOf(cur), S.answers[cur]);
    if (curMiss.length) { flagMissing(curMiss); return; }
  }
  if (PREVIEW) { showThanks(); return; }
  await Outbox.flush();
  if (Outbox.pending.size) { alert(T().leftover); return; }
  try { await apiPost({ action: 'finish', detail: { n_items: S.order.length } }); }
  catch (e) { alert(T().submitFail + e.message); return; }
  showThanks();
});

window.addEventListener('resize', () => {
  const card = document.querySelector('.item');
  if (card) syncRate(card);
});

boot();
